apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
        - image: duyhoang5891/udagram-reverse-proxy
          name: udagram-reverse-proxy
          imagePullPolicy: Always
          ports:
          - containerPort: 8080      
      restartPolicy: Always