apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-user
  name: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-user
  template:
    metadata:
      labels:
        service: udagram-api-user
    spec:
      containers:
        - image: duyhoang5891/udagram-api-user
          name: udagram-api-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2024Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret